openapi: 3.0.3
info:
  title: '[dx_vas Service] API Template'
  description: 'OpenAPI template chuẩn hóa dành cho các service thuộc hệ thống dx_vas.

    Tuân thủ ADR-009 đến ADR-013.'
  version: 0.1.0-legendary-template
  contact:
    name: DX VAS Platform Team
    email: dev@truongvietanh.edu.vn
servers:
- url: https://[subdomain].truongvietanh.edu.vn/api/v1
tags:
- name: '[Tên Tag Chính]'
  description: Các API liên quan đến [Mô tả Tag Chính].
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    ErrorResponse:
      description: Lỗi xảy ra trong quá trình xử lý
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEnvelope'
  schemas:
    ErrorEnvelope:
      type: object
      properties:
        error:
          type: object
          required:
          - code
          - message
          properties:
            code:
              type: string
              example: GENERIC_ERROR
            message:
              type: string
              example: Đã có lỗi xảy ra.
            details:
              type: object
              additionalProperties: true
        meta:
          $ref: '#/components/schemas/ResponseMeta'
    ResponseMeta:
      type: object
      required:
      - timestamp
      - trace_id
      properties:
        timestamp:
          type: string
          format: date-time
          description: Thời điểm phản hồi
        trace_id:
          type: string
          description: Mã trace ID để liên kết log/tracing
    StandardSuccessResponse_Example:
      type: object
      properties:
        data:
          type: object
          properties:
            example_field:
              type: string
              example: example value
        error:
          type: 'null'
          example: null
        meta:
          $ref: '#/components/schemas/ResponseMeta'
      description: Cấu trúc phản hồi thành công chuẩn theo ADR-012.
x-template-origin: dx_vas
