name: OpenAPI Validation

on:
  pull_request:
    paths:
      - '**/*.openapi.yaml'
  push:
    paths:
      - '**/*.openapi.yaml'

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Lint OpenAPI files
        run: spectral lint "**/*.openapi.yaml" --fail-severity warn